[hazard]
# Archivo de la fuente sísmica
source_model = source_model.xml

# Archivo con el modelo de atenuación
gsim_logic_tree = gsim_logic_tree.xml

# Archivo con la información del sitio
site_model = site_model.csv

# Carpeta donde se guardarán los resultados
output_dir = output
