# Generated by Django 5.2.8 on 2025-12-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=50, unique=True, verbose_name='ID Fuente (ISC-GEM)')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('magnitude', models.FloatField(verbose_name='Magnitud (Mw)')),
                ('depth', models.FloatField(verbose_name='Profundidad (km)')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('latitude', models.FloatField(verbose_name='Latitud Actual')),
                ('longitude', models.FloatField(verbose_name='Longitud Actual')),
                ('latitude_original', models.FloatField(default=0.0, verbose_name='Latitud Original')),
                ('longitude_original', models.FloatField(default=0.0, verbose_name='Longitud Original')),
                ('smajax', models.FloatField(default=0.0, verbose_name='Semieje Mayor (km)')),
                ('sminax', models.FloatField(default=0.0, verbose_name='Semieje Menor (km)')),
                ('strike', models.FloatField(default=0.0, verbose_name='Azimut/Strike (grados)')),
                ('unc', models.FloatField(default=0.0, verbose_name='Incertidumbre')),
                ('dip', models.FloatField(default=0.0, verbose_name='Dip')),
                ('rake', models.FloatField(default=0.0, verbose_name='Rake')),
                ('mo', models.FloatField(default=0.0, verbose_name='Momento Sísmico (Mo)')),
                ('mpp', models.FloatField(blank=True, default=0.0, null=True)),
                ('mrr', models.FloatField(blank=True, default=0.0, null=True)),
                ('mtt', models.FloatField(blank=True, default=0.0, null=True)),
                ('is_main_shock', models.BooleanField(default=True, verbose_name='Sismo Principal')),
            ],
            options={
                'verbose_name': 'Terremoto',
                'verbose_name_plural': 'Terremotos',
            },
        ),
        migrations.CreateModel(
            name='RecurrenceParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_name', models.CharField(default='Zona Iberia/Canarias', max_length=100, unique=True)),
                ('a_original', models.FloatField(default=0.0)),
                ('b_original', models.FloatField(default=0.0)),
                ('mc_original', models.FloatField(default=0.0)),
                ('lambda_original', models.FloatField(default=0.0)),
                ('tara_sismica_original', models.FloatField(default=0.0, verbose_name='Tara Original (Nm/año)')),
                ('a_edited', models.FloatField(default=0.0)),
                ('b_edited', models.FloatField(default=0.0)),
                ('mc_edited', models.FloatField(default=0.0)),
                ('lambda_edited', models.FloatField(default=0.0)),
                ('tara_sismica_edited', models.FloatField(default=0.0, verbose_name='Tara Editada (Nm/año)')),
            ],
            options={
                'verbose_name': 'Parámetro de Recurrencia',
                'verbose_name_plural': 'Parámetros de Recurrencia',
            },
        ),
        migrations.CreateModel(
            name='SeismicSourceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Zona Fuente')),
                ('a_param', models.FloatField(default=0.0)),
                ('b_param', models.FloatField(default=0.0)),
            ],
        ),
    ]
