# Generated by Django 5.2.8 on 2026-06-22 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecurrenceParameters',
        ),
        migrations.DeleteModel(
            name='SeismicSourceZone',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='dip',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='mo',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='mpp',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='mrr',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='mtt',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='rake',
        ),
        migrations.RemoveField(
            model_name='earthquake',
            name='unc',
        ),
    ]
